---

- name: Retrieve tenantID
  shell: openstack {{ AUTH_S }} --os-auth-url {{ OS_AUTH_URL_V3 }} --os-identity-api-version 3
         project list | awk '/ {{ tenantname }} / { print $2 }'
  register: tenantid

- name: Retrieve instance id from tenant
  shell: nova {{ AUTH_S }} --os-auth-url {{ OS_AUTH_URL_V2 }}
         list --all-tenants --tenant {{ tenantid.stdout }} --minimal | awk 'NR > 3 { print $2 }'
  register: instid

- name: Delete instanaces by tenant
  command: nova {{ AUTH_S }} --os-auth-url {{ OS_AUTH_URL_V2 }} 
           delete {{ item }}
  with_items: instid.stdout_lines

- name: Destroy user environments
  command: openstack {{ AUTH_S }} --os-auth-url {{ OS_AUTH_URL_V3 }} --os-identity-api-version 3
           project delete {{ tenantname }}
  ignore_errors: yes

- name: Delete users
  command: openstack {{ AUTH_S }} --os-auth-url {{ OS_AUTH_URL_V3 }} --os-identity-api-version 3 
           user delete {{ userid }}
  ignore_errors: yes