---

- name: Install random password generator package
  apt: name={{item}} state=present
  with_items:
   - apg

- name: Random generate passwords
  command: apg -n {{ pass_cnt }} -M NCL -q
  register: passwdss

- name: Create users
  command: openstack {{ AUTH_S }} --os-auth-url {{ OS_AUTH_URL_V3 }} --os-identity-api-version 3
           user create --password={{ item.1 }} {{ item.0 }}
  with_together:
    - userid
    - passwdss.stdout_lines

- name: Create user environments
  command: openstack {{ AUTH_S }} --os-auth-url {{ OS_AUTH_URL_V3 }} --os-identity-api-version 3
           project create --description="{{ item }}" {{ item }}
  with_items: tenantid

- name: Assign user to specified role in designated environment
  command: openstack {{ AUTH_S }} --os-auth-url {{ OS_AUTH_URL_V3 }} --os-identity-api-version 3
           role add --user={{ item.0 }} --project={{ item.1 }} {{ urole }}
  with_together: 
    - userid
    - tenantid
    
- name: User password assignment
  debug: msg="User {{ item.0 }} was added to {{ item.2 }} tenant, with the assigned password of {{ item.1 }}"
  with_together:
    - userid
    - passwdss.stdout_lines
    - tenantid